services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama

  indexer:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["python", "index_docs.py"]
    env_file:
      - .env
    depends_on:
      - db
      - ollama

  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
    depends_on:
      - backend

volumes:
  pgdata:
  ollama_data:
